//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSKinesisConnect.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5T90LiSeI9MRuD0/enF6jkMat9lCwjofbb01cSjc")]
        public string SecretAccess {
            get {
                return ((string)(this["SecretAccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AKIAIZCXABO5IS3VCZMQ")]
        public string AccessKey {
            get {
                return ((string)(this["AccessKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"FQoDYXdzEIf//////////wEaDBys1NFJPpqaZxjBoCKsAfA11WFUm7zVEJ/Bgrmequ5BFAuw1RXDer6m9n2Tze6FI+lTAyogNAqDGE+iFtSTuO15qeUlO/xubKRtTvA1AJ74DqMHm7MyFs0hikD5VQ+bKBG7nmGlUv96vg/2iY4gl2BGjX9y92DWIkZkxYTFH+ByXkvwbXqI7Yh+8bOd4MeUdroJZct7w/DoJVjQRBM61elltn50qH8lpU8ZvfUzn9nTm67zzS340W5dZ3Mood3f0wU=")]
        public string SessionToken {
            get {
                return ((string)(this["SessionToken"]));
            }
        }
    }
}
